---
- hosts: temperature_sensors
  pre_tasks:
    - name: Include private vars
      include_vars:
        dir: '../private/deploy/vars/'

  roles:
    - common
    # - temperature_sensor
    - ssh_tunnels
