---
- name: Create remote project directory {{ REMOTE_MA_DIRECTORY }}
  file: path={{ REMOTE_MA_DIRECTORY }} state=directory
  become: yes
  become_user: "{{ REMOTE_MA_USER }}"

- name: Update apt
  include_role:
    name: update_apt

- name: install rsync
  apt:
    name: rsync
    state: present
  become: yes
