---
- name: Restart machine
  become: yes
  shell: ( sleep 5 && reboot & )
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for the machine to reboot
  local_action:
    wait_for:
      delay: 5
