---
- name: Restart machine
  become: yes
  # TODO, fix this.  Restart doesn't work without sudo su and ansible gives a
  # warning that is apparently avoided and unnecessary
  shell: "sudo su -c \"sleep 2 && reboot &\""
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for the machine to reboot
  local_action: shell sleep 5
