---
# - name: Copy over code
#   synchronize:
#     src: "{{ LOCAL_PROJECT_DIRECTORY }}/./{{ item }}"
#     dest: "{{ REMOTE_PROJECT_DIRECTORY }}"
#     rsync_opts:
#       - "--relative"
#   with_items:
#     - lib/ABElectronics_Python3_Libraries/ADCPi/
#     - src/temperature_sensor/
#     - private/src/
